# Generated by Django 5.0.1 on 2024-03-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
